//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ipadsEntities : DbContext
    {
        public ipadsEntities()
            : base("name=ipadsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SpAllQandA_Result> SpAllQandA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAllQandA_Result>("SpAllQandA");
        }
    
        public virtual ObjectResult<SpAnsweredQ_Result> SpAnsweredQ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAnsweredQ_Result>("SpAnsweredQ");
        }
    
        public virtual ObjectResult<SpAuthen_Result> SpAuthen(string userName, string keyNo)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var keyNoParameter = keyNo != null ?
                new ObjectParameter("KeyNo", keyNo) :
                new ObjectParameter("KeyNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAuthen_Result>("SpAuthen", userNameParameter, keyNoParameter);
        }
    
        public virtual ObjectResult<SpInactiveSerach_Result> SpInactiveSerach(string locationName)
        {
            var locationNameParameter = locationName != null ?
                new ObjectParameter("LocationName", locationName) :
                new ObjectParameter("LocationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpInactiveSerach_Result>("SpInactiveSerach", locationNameParameter);
        }
    
        public virtual ObjectResult<string> SpInsertIC(Nullable<short> iPadID, string name)
        {
            var iPadIDParameter = iPadID.HasValue ?
                new ObjectParameter("iPadID", iPadID) :
                new ObjectParameter("iPadID", typeof(short));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SpInsertIC", iPadIDParameter, nameParameter);
        }
    
        public virtual int SpInsertQandA(string question)
        {
            var questionParameter = question != null ?
                new ObjectParameter("Question", question) :
                new ObjectParameter("Question", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpInsertQandA", questionParameter);
        }
    
        public virtual ObjectResult<SpReportSearch_Result> SpReportSearch(string locationName)
        {
            var locationNameParameter = locationName != null ?
                new ObjectParameter("LocationName", locationName) :
                new ObjectParameter("LocationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpReportSearch_Result>("SpReportSearch", locationNameParameter);
        }
    
        public virtual ObjectResult<SpSummary_Result> SpSummary(string locationName)
        {
            var locationNameParameter = locationName != null ?
                new ObjectParameter("LocationName", locationName) :
                new ObjectParameter("LocationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpSummary_Result>("SpSummary", locationNameParameter);
        }
    
        public virtual int SpUpdateQandA(Nullable<int> recID, string answer)
        {
            var recIDParameter = recID.HasValue ?
                new ObjectParameter("RecID", recID) :
                new ObjectParameter("RecID", typeof(int));
    
            var answerParameter = answer != null ?
                new ObjectParameter("Answer", answer) :
                new ObjectParameter("Answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpUpdateQandA", recIDParameter, answerParameter);
        }
    }
}
